# 1. Notifications
notifications:
  slack:
    rooms:
      # atex-ci
      - secure: "T35c1FWm+lTha+e+feLMbzjJzV+p9TbYt5H8v4qtHjXi/uADn+eoVXjxtnVQnEgQzkdxh/grvZarya3Z+IRjONDDBRKmyedbeJ+fIJLKM5MYA/B4IQd5lPBn7gl5mg+4vhksxOl8N6sXgluUyOKJXp97x4bs8/kNzl0Ac8+x8ocbtl1Nikhn7XlsCVeqhJIY5i3Naak+qAeqNB9PbX/9p+GN1DB0R8nGqGQdoXYpUuAZHDc1SMRTBbwDVAQ7faNTOxp3wWpn93jRunb5Z71DyrQXmk3gBqf0SiRwNVyPO+x9sxzzDlI4vabCbrYSIa5chOB2E7pAwuRFyyy2rtm/IKanlFsGygIHUvowzxSsqNj5ilT8ZYuHg8IrohHaRWy4+IHLYGt8wAHdmla4FCl4OG2eejUcD+33hHfEhUxryL4CU9sWmw1gRwuN0d5QC2IrkCwbOripEpdtLZg69vDWnjk8/HkPGgcU6ieY5wnGqqdXOsw8ZxIKeR6OXBfLZv2QAURt/IVIvOIJ4FDyERrqn3tCC9XnkLKQyFQ5Pophcn0T1EaxNaQDa85X9VP471prjxkpcCWGTPvDoDiFHcocrzfJ7SlHHJCUyylxP/na2oWu+/zi6sxjkHht+J7xyXjBY6l3R669843qMzdATkaeZe9MzBzTVIv7jSP3RuPJQtY="
      # cloud-ci
      - secure: "Z+gJUCvSishk17Dg8H+rHnADSw/aPaXK70malnUZPsbDDd+Pyc3xHsT1DtyMdhZRhNfFA0J7J05EVlYlmZUoMzcIfaooop9gaXtH/kQDrjkvZYEOgrW5qfjjEHXJcvYj0I6moSgXEw/eKX8ODt/giipqCE6qtFyGasnzTuwuvE6V8/n3zjrD0KA0LctWxMxAXrUJBgBg8r2bvBLff7igKIWL1gMOJtm7Rk8eOi2iWRqaOIkqRTtGFuKkmyhh+llUa+LRjGu8QoQxSS4JHq17adArRHYXNwmTbVg8FSLXSWjh7RRKmKMhYFG8Z1FqUiFSAE03lc98mum3BtNtIK2jvCYLDGuo6ecjd/6fu9F4jVAvS2McevSSmUmcRzYvohT1BlGpYGYLjwKrMtcrxN+qADr06h2Ww0itWWbN305yxoXE5YATlXT6WvSjqA9qUCdvGYyOEHmfQJqPN53Lmpt78yOPkgrZWE8VwEWc1Xckv9nY+YKvO56bomvOfScoLlMWUaejSslXNtNm93afCRkVY8wlxLuEyQIokAc0zwr+lPniutnr8Pxg7jOrewytJV1omMe5yCIe23E5oBkv28rIIPWJcEl1I8WmV0kPMTFlAeo6zZ8tGzNhB2A8v4mhRnUcwxg29XUQffqiITWRkb5PMU1i2NpoG4C9jbpJ8JY4xW0="
    on_success: change
    on_pull_requests: false

# 2. Env
# env:

# 3. Git
# git:
branches:
  except:
    - /^f\// # feature branches require PR
    - /^v\d+\.\d+\.\d+$/ # npm-publish-git

# 4. Bootstrap
os: linux
dist: xenial
language: generic
# addons:
before_cache: ./.travis.sh before_cache
cache:
  directories:
    # common
    - $HOME/.local
    - $HOME/.npm
    # darwin
    - $HOME/.homebrew
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip
    # linux
    - $HOME/.cache/Homebrew
    - $HOME/.cache/pip
    - $HOME/.linuxbrew

# 5. Steps
before_install: ./.travis.sh before_install
install: ./.travis.sh install
before_script: ./.travis.sh before_script
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

# 6. Deploy
before_deploy: ./.travis.sh before_deploy
# deploy:
after_deploy: ./.travis.sh after_deploy
